groupitems = [['GNGSA', [18]], ['GPGSV', [20]], ['GLGSV', [20, 16]], ['GNGGA', [9, 15]], ['GNZDA', [7]], ['GNRMC', [13]], ['GNGLL', [8]]]
sentencetypes = ['GNGLL', 'GNGSA', 'GNGGA', 'GNRMC', 'GLGSV', 'GPGSV', 'GNZDA']
maxlist = [['GNGSA', 18], ['GPGSV', 20], ['GLGSV', 20], ['GNGGA', 15], ['GNZDA', 7], ['GNRMC', 13], ['GNGLL', 8]]
GNGSAmax = 18
GPGSVmax = 20
GLGSVmax = 20
GNGGAmax = 15
GNZDAmax = 7
GNRMCmax = 13
GNGLLmax = 8
GNGSA = [18]
GPGSV = [20]
GLGSV = [20, 16]
GNGGA = [9, 15]
GNZDA = [7]
GNRMC = [13]
GNGLL = [8]
db = 'fileParser.db'
